import React,{useMemo,useState}from"react";
import AppLayout from"../layouts/AppLayout.jsx";
import ExecutiveCharts from"../components/ExecutiveCharts.jsx";
import{useLanguage}from"../i18n/LanguageContext.jsx";

function csvCell(value){return `"${String(value??"").replaceAll('"','""')}"`;}
export default function ReportsPage({user,leads,partners,opportunities,tasks,onNavigate,onLogout}){
 const{t,locale}=useLanguage(); const[owner,setOwner]=useState("all"); const[status,setStatus]=useState("all");
 const owners=[...new Set(opportunities.map(x=>x.owner).filter(Boolean))];
 const filtered=useMemo(()=>opportunities.filter(x=>(owner==="all"||x.owner===owner)&&(status==="all"||x.status===status)),[opportunities,owner,status]);
 const open=filtered.filter(x=>x.status==="Aberta"),won=filtered.filter(x=>x.status==="Ganha"),lost=filtered.filter(x=>x.status==="Perdida");
 const sum=(rows)=>rows.reduce((n,x)=>n+Number(x.value||0),0); const pipeline=sum(open); const weighted=open.reduce((n,x)=>n+Number(x.value||0)*Number(x.probability||0)/100,0);
 const conversion=opportunities.length?Math.round(won.length/opportunities.length*100):0; const today=new Date().toISOString().slice(0,10);
 const money=(n)=>new Intl.NumberFormat(locale,{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);
 function exportCsv(){const headers=[t("reports.opportunity"),t("reports.company"),t("reports.stage"),t("reports.status"),t("reports.owner"),t("reports.value"),t("reports.probability"),t("reports.weightedValue")];const rows=filtered.map(x=>[x.title,x.company,x.stage,x.status,x.owner,x.value,x.probability,Number(x.value||0)*Number(x.probability||0)/100]);const csv="\uFEFF"+[headers,...rows].map(r=>r.map(csvCell).join(";")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`nexa360-relatorio-${today}.csv`;a.click();URL.revokeObjectURL(url);}
 return <AppLayout user={user} activePage="reports" onNavigate={onNavigate} onLogout={onLogout} title={t("reports.title")}><div className="content reports-content">
  <section className="partners-hero report-hero"><div><p className="eyebrow light">{t("reports.eyebrow")}</p><h2>{t("reports.heading")}</h2><p>{t("reports.description")}</p></div><div className="report-actions"><button className="secondary-button light-button" onClick={()=>window.print()}>{t("reports.print")}</button><button className="new-partner-button" onClick={exportCsv}>{t("reports.export")}</button></div></section>
  <section className="report-meta"><span>{t("reports.generated",{date:new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date())})}</span><span>{t("reports.source")}</span></section>
  <section className="report-filters"><select value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">{t("reports.allOwners")}</option>{owners.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">{t("reports.allStatuses")}</option><option value="Aberta">{t("opportunities.statuses.Aberta")}</option><option value="Ganha">{t("opportunities.statuses.Ganha")}</option><option value="Perdida">{t("opportunities.statuses.Perdida")}</option></select></section>
  <p className="eyebrow report-section-title">{t("reports.summary")}</p><section className="report-kpis"><article><span>{t("reports.leads")}</span><strong>{leads.length}</strong></article><article><span>{t("reports.partners")}</span><strong>{partners.length}</strong></article><article><span>{t("reports.openDeals")}</span><strong>{open.length}</strong></article><article><span>{t("reports.pipeline")}</span><strong>{money(pipeline)}</strong></article><article><span>{t("reports.weighted")}</span><strong>{money(weighted)}</strong></article><article><span>{t("reports.conversion")}</span><strong>{conversion}%</strong></article><article><span>{t("reports.tasksDone")}</span><strong>{tasks.filter(x=>x.status==="completed").length}</strong></article><article><span>{t("reports.overdue")}</span><strong>{tasks.filter(x=>x.status!=="completed"&&x.dueDate<today).length}</strong></article></section>
  <section className="report-performance"><div><p className="eyebrow">{t("reports.performance")}</p><div className="performance-grid"><article><span>{t("reports.openValue")}</span><strong>{money(pipeline)}</strong></article><article><span>{t("reports.wonValue")}</span><strong>{money(sum(won))}</strong></article><article><span>{t("reports.lostValue")}</span><strong>{money(sum(lost))}</strong></article><article><span>{t("reports.averageTicket")}</span><strong>{money(filtered.length?sum(filtered)/filtered.length:0)}</strong></article></div></div></section>
  <ExecutiveCharts leads={leads} opportunities={filtered}/>
  <section className="partners-table-card report-table"><header><div><p className="eyebrow">{t("reports.reportTable")}</p><h2>{filtered.length}</h2></div></header><div className="partners-table-wrap"><table className="partners-table"><thead><tr><th>{t("reports.opportunity")}</th><th>{t("reports.company")}</th><th>{t("reports.stage")}</th><th>{t("reports.status")}</th><th>{t("reports.owner")}</th><th>{t("reports.value")}</th><th>{t("reports.weightedValue")}</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><strong>{x.title}</strong><small>#{x.id}</small></td><td>{x.company}</td><td>{t(`opportunities.stages.${x.stage}`)}</td><td>{t(`opportunities.statuses.${x.status}`)}</td><td>{x.owner}</td><td>{money(x.value)}</td><td>{money(Number(x.value||0)*Number(x.probability||0)/100)}</td></tr>)}</tbody></table></div>{!filtered.length&&<div className="empty-state">{t("reports.empty")}</div>}</section>
 </div></AppLayout>;
}
