import React,{useEffect,useState}from"react";
import AppLayout from"../layouts/AppLayout.jsx";
import{useLanguage}from"../i18n/LanguageContext.jsx";

const SETTINGS_KEY="nexa360_settings_v1",TARGET_KEY="nexa360_monthly_commercial_target",PROFILE_KEY="nexa360_profile_v1";
const APP_VERSION = "1.10.7";
const FISCAL_MONTHS=["january","february","march","april","may","june","july","august","september","october","november","december"];
const defaults={companyName:"NEXA360",taxId:"999999990",country:"Portugal",city:"Porto",website:"https://nexa360.pt",monthlyTarget:100000,currency:"EUR",fiscalYear:"january",notifications:true,compact:false};
function load(){try{return{...defaults,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}"),monthlyTarget:Number(localStorage.getItem(TARGET_KEY))||100000};}catch{return defaults;}}
export default function SettingsPage({user,onUpdateUser,leads,partners,opportunities,contacts,tasks,onNavigate,onLogout}){
 const{t,language,languages,setLanguage}=useLanguage(); const[section,setSection]=useState("profile"); const[settings,setSettings]=useState(load); const[profile,setProfile]=useState({name:user.name,email:user.email}); const[message,setMessage]=useState("");
 useEffect(()=>{document.body.classList.toggle("nexa-compact",settings.compact);return()=>document.body.classList.remove("nexa-compact");},[settings.compact]);
 const set=(key,value)=>setSettings(x=>({...x,[key]:value}));
 function save(event){event.preventDefault();if(!profile.name.trim()||!/^\S+@\S+\.\S+$/.test(profile.email))return setMessage(t("settings.required"));if(Number(settings.monthlyTarget)<=0)return setMessage(t("settings.targetRequired"));const savedProfile={name:profile.name.trim(),email:profile.email.trim()};localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));localStorage.setItem(TARGET_KEY,String(Number(settings.monthlyTarget)));localStorage.setItem(PROFILE_KEY,JSON.stringify(savedProfile));onUpdateUser({...user,...savedProfile});setMessage(t("settings.saved"));}
 function exportData(){const payload={exportedAt:new Date().toISOString(),application:"NEXA360 CRM Enterprise Demo",version:APP_VERSION,settings,records:{leads,partners,opportunities,contacts,tasks}};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`nexa360-demo-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);setMessage(t("settings.exported"));}
 const money=new Intl.NumberFormat(languages.find(x=>x.code===language)?.locale||"pt-PT",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(settings.monthlyTarget)||0);
 return <AppLayout user={user} activePage="settings" onNavigate={onNavigate} onLogout={onLogout} title={t("settings.title")}><div className="content settings-content">
  <section className="partners-hero"><div><p className="eyebrow light">{t("settings.eyebrow")}</p><h2>{t("settings.heading")}</h2><p>{t("settings.description")}</p></div><div className="settings-version"><small>{t("settings.version")}</small><strong>v{APP_VERSION}</strong></div></section>
  <aside className="settings-warning"><span>🛡</span><div><strong>{t("settings.publicWarning")}</strong><p>{t("settings.publicText")}</p></div></aside>
  <div className="settings-layout"><nav className="settings-nav">{[["profile","◉"],["company","◇"],["commercial","↗"],["preferences","⚙"],["data","▥"]].map(([id,icon])=><button key={id} className={section===id?"active":""} onClick={()=>{setSection(id);setMessage("");}}><span>{icon}</span>{t(`settings.${id}`)}</button>)}</nav>
  <form className="settings-panel" onSubmit={save}>
   {section==="profile"&&<><header><p className="eyebrow">{t("settings.profile")}</p><h2>{profile.name}</h2><p>{t("settings.profileHelp")}</p></header><div className="settings-grid"><label><span>{t("settings.name")}</span><input maxLength="80" value={profile.name} onChange={e=>setProfile(x=>({...x,name:e.target.value}))}/></label><label><span>{t("settings.email")}</span><input type="email" maxLength="160" value={profile.email} onChange={e=>setProfile(x=>({...x,email:e.target.value}))}/></label><label><span>{t("settings.role")}</span><input value={t("settings.roleAdmin")} disabled/></label></div></>}
   {section==="company"&&<><header><p className="eyebrow">{t("settings.company")}</p><h2>{settings.companyName}</h2><p>{t("settings.companyHelp")}</p></header><div className="settings-grid"><label><span>{t("settings.companyName")}</span><input maxLength="120" value={settings.companyName} onChange={e=>set("companyName",e.target.value)}/></label><label><span>{t("settings.taxId")}</span><input maxLength="20" value={settings.taxId} onChange={e=>set("taxId",e.target.value)}/></label><label><span>{t("settings.country")}</span><input maxLength="80" value={settings.country} onChange={e=>set("country",e.target.value)}/></label><label><span>{t("settings.city")}</span><input maxLength="80" value={settings.city} onChange={e=>set("city",e.target.value)}/></label><label className="settings-wide"><span>{t("settings.website")}</span><input maxLength="180" value={settings.website} onChange={e=>set("website",e.target.value)}/></label></div></>}
   {section==="commercial"&&<><header><p className="eyebrow">{t("settings.commercial")}</p><h2>{money}</h2><p>{t("settings.commercialHelp")}</p></header><div className="settings-grid"><label><span>{t("settings.monthlyTarget")}</span><input type="number" min="1" step="1000" value={settings.monthlyTarget} onChange={e=>set("monthlyTarget",e.target.value)}/></label><label><span>{t("settings.currency")}</span><select value={settings.currency} onChange={e=>set("currency",e.target.value)}><option value="EUR">{t("settings.eur")}</option><option value="USD">{t("settings.usd")}</option><option value="GBP">{t("settings.gbp")}</option></select></label><label><span>{t("settings.fiscalYear")}</span><select value={settings.fiscalYear} onChange={e=>set("fiscalYear",e.target.value)}>{FISCAL_MONTHS.map(x=><option key={x} value={x}>{t(`settings.${x}`)}</option>)}</select></label></div></>}
   {section==="preferences"&&<><header><p className="eyebrow">{t("settings.preferences")}</p><h2>{t("settings.language")}</h2></header><div className="settings-grid"><label><span>{t("settings.language")}</span><select value={language} onChange={e=>setLanguage(e.target.value)}>{languages.map(x=><option key={x.code} value={x.code}>{x.label}</option>)}</select></label><label className="setting-toggle"><input type="checkbox" checked={settings.notifications} onChange={e=>set("notifications",e.target.checked)}/><span><strong>{t("settings.notifications")}</strong></span></label><label className="setting-toggle"><input type="checkbox" checked={settings.compact} onChange={e=>set("compact",e.target.checked)}/><span><strong>{t("settings.compact")}</strong></span></label></div></>}
   {section==="data"&&<><header><p className="eyebrow">{t("settings.data")}</p><h2>{t("settings.records")}</h2><p>{t("settings.exportHelp")}</p></header><div className="settings-records">{[["leads",leads.length],["partners",partners.length],["opportunities",opportunities.length],["contacts",contacts.length],["tasks",tasks.length]].map(([key,value])=><article key={key}><span>{t(`settings.${key}`)}</span><strong>{value}</strong></article>)}</div><div className="settings-security"><strong>🛡 {t("settings.security")}</strong><p>{t("settings.session")}</p><p>{t("settings.storage")}</p></div><button type="button" className="secondary-button export-backup" onClick={exportData}>{t("settings.export")}</button></>}
   <footer className="settings-footer"><span className="settings-message">{message}</span>{section!=="data"&&<button className="primary-action">{t("settings.save")}</button>}</footer>
  </form></div>
 </div></AppLayout>;
}
